import { RadarData } from "@/components/ui/SpiderThreatRadar";

export interface StockItem {
  ticker: string;
  name: string;
  price: string;
  change: string;
  isPositive: boolean;
  sector: string;
  category: "NIFTY 50" | "SENSEX 30" | "NIFTY NEXT 50" | "HIGH BETA & F&O" | "MIDCAP ALPHA";
  data: RadarData;
  quantAnalysis: {
    greeks: string;
    pcr: number;
    support: string;
    resistance: string;
    summary: string;
  };
  regulatoryAnalysis: {
    sebiFilings: string;
    governanceScore: number;
    insiderActivity: string;
    auditorNotes: string;
  };
  sentimentAnalysis: {
    fiiFlowText: string;
    socialScore: number;
    newsPolarity: string;
    macroContext: string;
  };
  targetPrice: string;
  stopLoss: string;
  timeHorizon: string;
}

// 150 Indian Stock Market Companies
export const TOP_150_STOCKS: StockItem[] = [
  // --- NIFTY 50 / SENSEX 30 Heavyweights ---
  {
    ticker: "RELIANCE",
    name: "Reliance Industries Ltd",
    price: "₹2,940.50",
    change: "+2.4%",
    isPositive: true,
    sector: "Energy & Telecom",
    category: "NIFTY 50",
    data: { volatility: 36, fiiFlow: 3240, momentum: 2.8 },
    quantAnalysis: {
      greeks: "Delta +0.68, Gamma neutral, low IV crush risk (IV: 16.2%)",
      pcr: 1.28,
      support: "₹2,880",
      resistance: "₹3,020",
      summary: "Clean algorithmic breakout with institutional volume absorption.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/RIL-EXP: Clean green energy CAPEX approvals verified.",
      governanceScore: 94,
      insiderActivity: "Promoter holding stable at 50.3%; zero pledge liabilities.",
      auditorNotes: "Unqualified audit report with clean cash flow reconciliations.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Net FII Institutional Inflow: +₹3,240 Cr in last 48 hours.",
      socialScore: 88,
      newsPolarity: "92% Positive across 14 financial news wires.",
      macroContext: "Crude oil stability provides margin headroom.",
    },
    targetPrice: "₹3,180.00 (+8.1%)",
    stopLoss: "₹2,860.00 (-2.7%)",
    timeHorizon: "2-4 Weeks Swing / Institutional Accumulation",
  },
  {
    ticker: "TCS",
    name: "Tata Consultancy Services Ltd",
    price: "₹4,185.00",
    change: "+1.2%",
    isPositive: true,
    sector: "Information Technology",
    category: "NIFTY 50",
    data: { volatility: 22, fiiFlow: 1450, momentum: 1.6 },
    quantAnalysis: {
      greeks: "Delta +0.55, lowest standard deviation band in IT basket",
      pcr: 1.15,
      support: "₹4,100",
      resistance: "₹4,320",
      summary: "Low-beta institutional defensive holding. Strong cash yield.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/TCS-Q3: Multi-billion dollar GenAI enterprise pipeline verified.",
      governanceScore: 98,
      insiderActivity: "Tata Sons holding rock-solid at 71.8%.",
      auditorNotes: "Impeccable audit compliance records.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Inflow: +₹1,450 Cr steady defensive allocation.",
      socialScore: 78,
      newsPolarity: "84% Bullish on US BFSI IT spending recovery.",
      macroContext: "USD/INR stability benefits operating margin.",
    },
    targetPrice: "₹4,450.00 (+6.3%)",
    stopLoss: "₹4,050.00 (-3.2%)",
    timeHorizon: "1-3 Months Safe Value",
  },
  {
    ticker: "HDFCBANK",
    name: "HDFC Bank Ltd",
    price: "₹1,640.00",
    change: "+0.8%",
    isPositive: true,
    sector: "Banking & Finance",
    category: "SENSEX 30",
    data: { volatility: 24, fiiFlow: 920, momentum: 0.9 },
    quantAnalysis: {
      greeks: "Delta +0.45, lowest IV in NIFTY 50 (12.4%), steady theta decay",
      pcr: 1.12,
      support: "₹1,600",
      resistance: "₹1,720",
      summary: "Ultra low beta defensive asset. Zero liquidation threat.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/RBI Merger Transition metrics meeting regulatory benchmarks.",
      governanceScore: 98,
      insiderActivity: "Zero promoter pledges; high institutional tier 1 capital.",
      auditorNotes: "Gold-standard banking audit compliance with zero discrepancies.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Consistent FII Inflow: +₹920 Cr gradual accumulation.",
      socialScore: 74,
      newsPolarity: "78% Positive; steady credit growth focus.",
      macroContext: "RBI interest rate pause supportive of net interest margins.",
    },
    targetPrice: "₹1,850.00 (+12.8%)",
    stopLoss: "₹1,580.00 (-3.6%)",
    timeHorizon: "Defensive Value / 1-6 Months",
  },
  {
    ticker: "INFY",
    name: "Infosys Ltd",
    price: "₹1,880.00",
    change: "+1.9%",
    isPositive: true,
    sector: "Information Technology",
    category: "NIFTY 50",
    data: { volatility: 32, fiiFlow: 1890, momentum: 2.1 },
    quantAnalysis: {
      greeks: "Delta +0.62, Call open interest unwinding at 1,860",
      pcr: 1.22,
      support: "₹1,820",
      resistance: "₹1,950",
      summary: "Algorithmic momentum turning bullish on large deal signings.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/INFY-DEAL: Topaz AI revenue contribution +34% YoY.",
      governanceScore: 96,
      insiderActivity: "Zero promoter pledges, independent board majority.",
      auditorNotes: "Clean audit with standard international accounting standards.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Net FII Buy: +₹1,890 Cr over 3 consecutive sessions.",
      socialScore: 82,
      newsPolarity: "88% Positive analyst upgrade consensus.",
      macroContext: "Global cloud migration spending re-accelerating.",
    },
    targetPrice: "₹2,050.00 (+9.0%)",
    stopLoss: "₹1,810.00 (-3.7%)",
    timeHorizon: "2-4 Weeks Swing",
  },
  {
    ticker: "ICICIBANK",
    name: "ICICI Bank Ltd",
    price: "₹1,260.00",
    change: "+1.5%",
    isPositive: true,
    sector: "Banking & Finance",
    category: "NIFTY 50",
    data: { volatility: 28, fiiFlow: 2150, momentum: 1.8 },
    quantAnalysis: {
      greeks: "Delta +0.64, solid Put wall accumulation at 1,220",
      pcr: 1.34,
      support: "₹1,220",
      resistance: "₹1,320",
      summary: "Industry-leading return on assets (RoA 2.3%). Top institutional pick.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/RBI Filing: Net NPA lowest in private banking sector (0.42%).",
      governanceScore: 95,
      insiderActivity: "Institutional ownership at 89%; zero promoter drag.",
      auditorNotes: "Clean banking audit reconciliations.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Aggressive FII Buying: +₹2,150 Cr monthly net addition.",
      socialScore: 86,
      newsPolarity: "94% Bullish across equity research desks.",
      macroContext: "Robust Indian domestic credit expansion cycle.",
    },
    targetPrice: "₹1,380.00 (+9.5%)",
    stopLoss: "₹1,215.00 (-3.5%)",
    timeHorizon: "1-2 Months Swing",
  },
  {
    ticker: "BHARTIARTL",
    name: "Bharti Airtel Ltd",
    price: "₹1,690.00",
    change: "+3.1%",
    isPositive: true,
    sector: "Telecom",
    category: "SENSEX 30",
    data: { volatility: 42, fiiFlow: 2780, momentum: 3.6 },
    quantAnalysis: {
      greeks: "Delta +0.76, Gamma expansion on ARPU tariff hikes",
      pcr: 1.48,
      support: "₹1,620",
      resistance: "₹1,780",
      summary: "Strong breakout velocity above key multi-month resistance.",
    },
    regulatoryAnalysis: {
      sebiFilings: "TRAI/SEBI Filing: ARPU increased to ₹245 with 5G monetization.",
      governanceScore: 92,
      insiderActivity: "Singtel and Bharti Enterprises holding stable.",
      auditorNotes: "Clean accounting of deferred spectrum liabilities.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Heavy FII Inflow: +₹2,780 Cr telecom reallocation.",
      socialScore: 89,
      newsPolarity: "95% Bullish on domestic duopoly cash flows.",
      macroContext: "Pricing power in Indian mobile data consumption.",
    },
    targetPrice: "₹1,850.00 (+9.4%)",
    stopLoss: "₹1,610.00 (-4.7%)",
    timeHorizon: "2-4 Weeks Breakout",
  },
  {
    ticker: "ITC",
    name: "ITC Ltd",
    price: "₹492.00",
    change: "+0.4%",
    isPositive: true,
    sector: "FMCG / Hotels / Paper",
    category: "NIFTY 50",
    data: { volatility: 18, fiiFlow: 650, momentum: 0.6 },
    quantAnalysis: {
      greeks: "Delta +0.38, rock-bottom volatility index (IV: 11.2%)",
      pcr: 1.08,
      support: "₹475",
      resistance: "₹515",
      summary: "Highest dividend yield security in index. Solid defensive buffer.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/NCLT: Hotel demerger scheme completed smoothly.",
      governanceScore: 97,
      insiderActivity: "Institutional holding stable across LIC & foreign funds.",
      auditorNotes: "Unqualified audit report with pristine cash balance.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Moderate FII Inflow: +₹650 Cr defensive positioning.",
      socialScore: 72,
      newsPolarity: "80% Positive on FMCG volume uptick.",
      macroContext: "Rural consumption revival post-monsoon.",
    },
    targetPrice: "₹540.00 (+9.7%)",
    stopLoss: "₹470.00 (-4.4%)",
    timeHorizon: "2-6 Months Defensive",
  },
  {
    ticker: "SBIN",
    name: "State Bank of India",
    price: "₹825.00",
    change: "+1.8%",
    isPositive: true,
    sector: "PSU Banking",
    category: "NIFTY 50",
    data: { volatility: 45, fiiFlow: 1950, momentum: 2.2 },
    quantAnalysis: {
      greeks: "Delta +0.65, strong call writing absorption at 810",
      pcr: 1.25,
      support: "₹795",
      resistance: "₹860",
      summary: "PSU banking leader with pristine loan book and record ROE.",
    },
    regulatoryAnalysis: {
      sebiFilings: "RBI/SEBI Disclosure: Gross NPA below 2.1%, PCR over 75%.",
      governanceScore: 90,
      insiderActivity: "Govt holding stable at 57.5%.",
      auditorNotes: "Clean public sector banking statutory audit.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Net FII & DII Inflow: +₹1,950 Cr institutional accumulation.",
      socialScore: 84,
      newsPolarity: "89% Bullish on credit growth and treasury yields.",
      macroContext: "Infrastructure capex lending surging.",
    },
    targetPrice: "₹920.00 (+11.5%)",
    stopLoss: "₹785.00 (-4.8%)",
    timeHorizon: "1-3 Months Value",
  },
  {
    ticker: "LT",
    name: "Larsen & Toubro Ltd",
    price: "₹3,720.00",
    change: "+2.2%",
    isPositive: true,
    sector: "Infrastructure & Defense",
    category: "SENSEX 30",
    data: { volatility: 38, fiiFlow: 2450, momentum: 2.5 },
    quantAnalysis: {
      greeks: "Delta +0.69, order book momentum accelerating",
      pcr: 1.30,
      support: "₹3,600",
      resistance: "₹3,900",
      summary: "Record ₹5.2 lakh crore order backlog. Solid multi-year visibility.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/LT-DEF: Mega defense & green hydrogen orders bagged.",
      governanceScore: 95,
      insiderActivity: "Professionally managed trust structure, zero promoter issues.",
      auditorNotes: "Comprehensive clean international audit.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Net Inflow: +₹2,450 Cr heavy industrial allocation.",
      socialScore: 87,
      newsPolarity: "93% Positive on capex super-cycle.",
      macroContext: "India National Infrastructure Pipeline execution on track.",
    },
    targetPrice: "₹4,100.00 (+10.2%)",
    stopLoss: "₹3,560.00 (-4.3%)",
    timeHorizon: "1-3 Months Growth",
  },
  {
    ticker: "TATAMOTORS",
    name: "Tata Motors Ltd",
    price: "₹980.00",
    change: "+2.7%",
    isPositive: true,
    sector: "Automotive & EV",
    category: "NIFTY 50",
    data: { volatility: 48, fiiFlow: 2200, momentum: 3.2 },
    quantAnalysis: {
      greeks: "Delta +0.72, Call Gamma trigger active above 960",
      pcr: 1.38,
      support: "₹940",
      resistance: "₹1,040",
      summary: "JLR free cash flow and domestic EV market share dominance.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/TAMO-DEM: Commercial vs Passenger vehicle demerger approved.",
      governanceScore: 94,
      insiderActivity: "Tata Sons pledge eliminated completely.",
      auditorNotes: "Clean JLR and domestic debt reduction audits.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Inflow: +₹2,200 Cr automotive momentum.",
      socialScore: 90,
      newsPolarity: "92% Positive on electric vehicle pipeline.",
      macroContext: "Raw material lithium & steel price moderation.",
    },
    targetPrice: "₹1,120.00 (+14.2%)",
    stopLoss: "₹930.00 (-5.1%)",
    timeHorizon: "2-4 Weeks Swing",
  },

  // --- High Beta & Quick Commerce & Fintech Disruptors ---
  {
    ticker: "ZOMATO",
    name: "Zomato Ltd (Eternal)",
    price: "₹268.40",
    change: "+5.6%",
    isPositive: true,
    sector: "Quick Commerce & Tech",
    category: "HIGH BETA & F&O",
    data: { volatility: 64, fiiFlow: 1950, momentum: 4.8 },
    quantAnalysis: {
      greeks: "Delta +0.82, Gamma squeeze active above ₹260 Call strike",
      pcr: 1.45,
      support: "₹250",
      resistance: "₹290",
      summary: "High kinetic breakout velocity. Volume 3.2x 20-day average.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/ZOM-Q2: Blinkit gross order value expansion +112% YoY.",
      governanceScore: 86,
      insiderActivity: "Key executives vesting exercised without open-market dumps.",
      auditorNotes: "Clean revenue recognition and EBITDA margin expansion.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Foreign Institutional Inflow: +₹1,950 Cr momentum purchase.",
      socialScore: 92,
      newsPolarity: "96% Bullish coverage on Blinkit quick-commerce capture.",
      macroContext: "Indian urban discretionary consumption at record high.",
    },
    targetPrice: "₹315.00 (+17.3%)",
    stopLoss: "₹252.00 (-6.1%)",
    timeHorizon: "Momentum Breakout / 1-3 Weeks",
  },
  {
    ticker: "PAYTM",
    name: "One97 Communications Ltd",
    price: "₹385.20",
    change: "-4.8%",
    isPositive: false,
    sector: "Fintech & Payments",
    category: "HIGH BETA & F&O",
    data: { volatility: 88, fiiFlow: -2850, momentum: -4.2 },
    quantAnalysis: {
      greeks: "Delta -0.74, massive IV spike (58.4%), extreme Gamma slip risk",
      pcr: 0.42,
      support: "₹340",
      resistance: "₹420",
      summary: "Severe order book imbalance. Institutional dark-pool dumping.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/RBI Enforcement Circulars pending compliance review.",
      governanceScore: 41,
      insiderActivity: "Significant institutional stakeholder dilution noted.",
      auditorNotes: "Related-party compliance and licensing contingency flags.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Heavy FII Net Liquidation: -₹2,850 Cr over 5 sessions.",
      socialScore: 18,
      newsPolarity: "84% Negative; elevated regulatory scrutiny narrative.",
      macroContext: "Fintech sector cost of compliance increasing.",
    },
    targetPrice: "NOT RECOMMENDED (DOWNWARD DRIFT)",
    stopLoss: "IMMEDIATE LIQUIDATION / HEDGE REQUIRED",
    timeHorizon: "EXTREME AVOIDANCE // TOXIC TRAP",
  },
  {
    ticker: "SUZLON",
    name: "Suzlon Energy Ltd",
    price: "₹68.50",
    change: "+4.2%",
    isPositive: true,
    sector: "Renewable Energy",
    category: "HIGH BETA & F&O",
    data: { volatility: 78, fiiFlow: 1420, momentum: 4.5 },
    quantAnalysis: {
      greeks: "Delta +0.85, massive retail call volume with institutional base",
      pcr: 1.52,
      support: "₹62.00",
      resistance: "₹76.00",
      summary: "Turnaround company with zero net debt and 4GW order backlog.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/SUZ-ORD: 1,166 MW wind turbine order win verified.",
      governanceScore: 81,
      insiderActivity: "Promoter shareholding stabilized post debt-restructuring.",
      auditorNotes: "Debt-free balance sheet verified by statutory auditors.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Inflow: +₹1,420 Cr clean energy momentum.",
      socialScore: 94,
      newsPolarity: "91% Bullish on national renewable target of 500GW.",
      macroContext: "Government sovereign solar/wind tenders accelerating.",
    },
    targetPrice: "₹84.00 (+22.6%)",
    stopLoss: "₹61.50 (-10.2%)",
    timeHorizon: "High Beta Swing / 2-6 Weeks",
  },
  {
    ticker: "ADANIENT",
    name: "Adani Enterprises Ltd",
    price: "₹3,120.00",
    change: "+1.9%",
    isPositive: true,
    sector: "Infrastructure Conglomerate",
    category: "NIFTY 50",
    data: { volatility: 66, fiiFlow: 1850, momentum: 3.8 },
    quantAnalysis: {
      greeks: "Delta +0.70, Gamma acceleration above 3,050 breakout pivot",
      pcr: 1.26,
      support: "₹2,980",
      resistance: "₹3,350",
      summary: "Navi Mumbai airport and green hydrogen capex driving growth.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/SC Investigation status clean; sovereign fund debt refinanced.",
      governanceScore: 78,
      insiderActivity: "Promoter pledge reduced significantly.",
      auditorNotes: "Tier-1 auditor appointment across key subsidiaries.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Net Inflow: +₹1,850 Cr institutional re-entry.",
      socialScore: 76,
      newsPolarity: "82% Bullish on airport traffic & mining volume growth.",
      macroContext: "Domestic capex super-cycle beneficiary.",
    },
    targetPrice: "₹3,550.00 (+13.7%)",
    stopLoss: "₹2,950.00 (-5.4%)",
    timeHorizon: "2-4 Weeks Breakout",
  },
  {
    ticker: "TATASTEEL",
    name: "Tata Steel Ltd",
    price: "₹148.50",
    change: "-1.8%",
    isPositive: false,
    sector: "Metals & Mining",
    category: "NIFTY 50",
    data: { volatility: 72, fiiFlow: -1450, momentum: -1.6 },
    quantAnalysis: {
      greeks: "Delta -0.52, Call resistance heavy at ₹155 strike",
      pcr: 0.76,
      support: "₹140",
      resistance: "₹155",
      summary: "Options gamma breakdown with lack of institutional buyers.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/TS-UK: Restructuring provisions impacting European ops.",
      governanceScore: 82,
      insiderActivity: "Holding steady, but debt metrics elevated.",
      auditorNotes: "European plant decarbonization impairment disclosures noted.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Outflow: -₹1,450 Cr cyclicals rotation.",
      socialScore: 42,
      newsPolarity: "65% Bearish on global steel export pricing.",
      macroContext: "China real-estate weakness dampening regional margins.",
    },
    targetPrice: "AVOID ENTRY UNTIL COMMODITY REVERSAL",
    stopLoss: "STRICT STOP AT ₹142",
    timeHorizon: "HIGH RISK / STAND ASIDE",
  },
  {
    ticker: "JIOFIN",
    name: "Jio Financial Services Ltd",
    price: "₹342.00",
    change: "+3.8%",
    isPositive: true,
    sector: "Non-Banking Financials (NBFC)",
    category: "NIFTY NEXT 50",
    data: { volatility: 54, fiiFlow: 2600, momentum: 4.1 },
    quantAnalysis: {
      greeks: "Delta +0.78, massive institutional call volume at 350 strike",
      pcr: 1.42,
      support: "₹320",
      resistance: "₹375",
      summary: "BlackRock JV asset management launch driving re-rating.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI In-Principle approval for mutual fund operations with BlackRock.",
      governanceScore: 95,
      insiderActivity: "Zero debt, massive ₹1.2 lakh crore net worth base.",
      auditorNotes: "Pristine statutory audit compliance.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Accumulation: +₹2,600 Cr high-conviction buy.",
      socialScore: 93,
      newsPolarity: "97% Bullish on digital lending & broking rollout.",
      macroContext: "Democratization of financial products across Jio 450M subscriber base.",
    },
    targetPrice: "₹420.00 (+22.8%)",
    stopLoss: "₹318.00 (-7.0%)",
    timeHorizon: "1-3 Months Growth",
  },
  {
    ticker: "HAL",
    name: "Hindustan Aeronautics Ltd",
    price: "₹4,680.00",
    change: "+3.4%",
    isPositive: true,
    sector: "Defense Aerospace",
    category: "NIFTY NEXT 50",
    data: { volatility: 58, fiiFlow: 2340, momentum: 4.4 },
    quantAnalysis: {
      greeks: "Delta +0.81, open interest breakout on Tejas Mk1A delivery schedule",
      pcr: 1.50,
      support: "₹4,450",
      resistance: "₹5,100",
      summary: "Defense order book at record ₹1.2 lakh crore with zero debt.",
    },
    regulatoryAnalysis: {
      sebiFilings: "MoD / SEBI Contract: ₹26,000 Cr Su-30MKI engine upgrade contract verified.",
      governanceScore: 93,
      insiderActivity: "Sovereign 71.6% holding, high dividend payout.",
      auditorNotes: "Clean statutory public defense audit.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Defense Inflow: +₹2,340 Cr strategic holding.",
      socialScore: 91,
      newsPolarity: "96% Bullish on indigenous defense manufacturing mandate.",
      macroContext: "Indian defense budget capital acquisition expansion.",
    },
    targetPrice: "₹5,350.00 (+14.3%)",
    stopLoss: "₹4,420.00 (-5.5%)",
    timeHorizon: "2-6 Weeks Breakout",
  },
  {
    ticker: "TRENT",
    name: "Trent Ltd (Westside & Zudio)",
    price: "₹7,250.00",
    change: "+4.1%",
    isPositive: true,
    sector: "Retail & Consumer Discretionary",
    category: "NIFTY 50",
    data: { volatility: 60, fiiFlow: 2900, momentum: 4.9 },
    quantAnalysis: {
      greeks: "Delta +0.84, highest momentum score in retail sector",
      pcr: 1.62,
      support: "₹6,900",
      resistance: "₹7,800",
      summary: "Zudio store expansion +50% YoY. Exponential store unit economics.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/TRNT-EXP: 200+ new Zudio and Westside stores added FY26.",
      governanceScore: 96,
      insiderActivity: "Tata Group backing with pristine corporate governance.",
      auditorNotes: "Clean lease accounting and margin expansion verification.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Heavy Institutional Inflow: +₹2,900 Cr continuous buying.",
      socialScore: 95,
      newsPolarity: "98% Positive equity broker upgrades.",
      macroContext: "Youth fast-fashion consumption boom in Tier-2/3 cities.",
    },
    targetPrice: "₹8,200.00 (+13.1%)",
    stopLoss: "₹6,850.00 (-5.5%)",
    timeHorizon: "1-2 Months Alpha Surge",
  },
  {
    ticker: "BEL",
    name: "Bharat Electronics Ltd",
    price: "₹298.00",
    change: "+2.6%",
    isPositive: true,
    sector: "Defense Electronics",
    category: "NIFTY 50",
    data: { volatility: 44, fiiFlow: 1800, momentum: 3.1 },
    quantAnalysis: {
      greeks: "Delta +0.71, Put base strong at 285 level",
      pcr: 1.36,
      support: "₹285",
      resistance: "₹325",
      summary: "Defense electronics radars and missile systems supplier with 24% EBITDA margin.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/BEL-ORD: ₹5,900 Cr radar & electronic warfare orders bagged.",
      governanceScore: 94,
      insiderActivity: "Zero debt, massive cash reserves.",
      auditorNotes: "Clean CAG and statutory audit approvals.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Net Inflow: +₹1,800 Cr institutional defense positioning.",
      socialScore: 88,
      newsPolarity: "94% Bullish coverage.",
      macroContext: "Make in India defense indigenization list.",
    },
    targetPrice: "₹340.00 (+14.0%)",
    stopLoss: "₹282.00 (-5.3%)",
    timeHorizon: "1-3 Months Growth",
  },
  {
    ticker: "SUNPHARMA",
    name: "Sun Pharmaceutical Industries Ltd",
    price: "₹1,895.00",
    change: "+1.4%",
    isPositive: true,
    sector: "Healthcare & Pharmaceuticals",
    category: "NIFTY 50",
    data: { volatility: 26, fiiFlow: 1650, momentum: 1.7 },
    quantAnalysis: {
      greeks: "Delta +0.58, steady low-beta accumulation",
      pcr: 1.20,
      support: "₹1,840",
      resistance: "₹1,980",
      summary: "Global specialty pipeline (Ilumya, Cequa, Winlevi) driving high margins.",
    },
    regulatoryAnalysis: {
      sebiFilings: "USFDA / SEBI: Specialty dermatology drug approvals granted.",
      governanceScore: 91,
      insiderActivity: "Promoter shareholding rock steady at 54.5%.",
      auditorNotes: "Clean R&D and global plant compliance records.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Consistent FII Buy: +₹1,650 Cr healthcare rotation.",
      socialScore: 80,
      newsPolarity: "89% Bullish on US specialty business growth.",
      macroContext: "Defensive sector hedge against market volatility.",
    },
    targetPrice: "₹2,100.00 (+10.8%)",
    stopLoss: "₹1,820.00 (-3.9%)",
    timeHorizon: "1-3 Months Defensive Growth",
  },
  {
    ticker: "MARUTI",
    name: "Maruti Suzuki India Ltd",
    price: "₹12,450.00",
    change: "+1.1%",
    isPositive: true,
    sector: "Automobile",
    category: "SENSEX 30",
    data: { volatility: 30, fiiFlow: 1380, momentum: 1.4 },
    quantAnalysis: {
      greeks: "Delta +0.52, strong Put base at 12,000 strike",
      pcr: 1.18,
      support: "₹12,000",
      resistance: "₹13,200",
      summary: "Dominant 42% Indian passenger vehicle market share leader.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/MAR-EV: eVX electric SUV manufacturing kickoff verified.",
      governanceScore: 96,
      insiderActivity: "Suzuki Motor Corporation 58.2% parent holding.",
      auditorNotes: "Unqualified statutory audit report.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Inflow: +₹1,380 Cr steady automotive investment.",
      socialScore: 79,
      newsPolarity: "85% Positive on hybrid & SUV mix expansion.",
      macroContext: "Festival season auto retail inventory normalization.",
    },
    targetPrice: "₹13,800.00 (+10.8%)",
    stopLoss: "₹11,900.00 (-4.4%)",
    timeHorizon: "1-3 Months Safe Value",
  },
  {
    ticker: "TITAN",
    name: "Titan Company Ltd",
    price: "₹3,480.00",
    change: "+2.0%",
    isPositive: true,
    sector: "Consumer Discretionary & Jewellery",
    category: "NIFTY 50",
    data: { volatility: 34, fiiFlow: 1720, momentum: 2.3 },
    quantAnalysis: {
      greeks: "Delta +0.64, Call buying surge on customs duty reduction",
      pcr: 1.28,
      support: "₹3,380",
      resistance: "₹3,680",
      summary: "Tanishq jewellery buyer surge + CaratLane omnichannel growth.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/TIT-Q2: Gold volume sales +28% YoY post duty cut.",
      governanceScore: 97,
      insiderActivity: "Tata Sons & TIDCO joint promoter holding stable.",
      auditorNotes: "Clean inventory and hedging audit reconciliations.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Net FII Buy: +₹1,720 Cr consumer luxury addition.",
      socialScore: 88,
      newsPolarity: "93% Positive wedding season demand outlook.",
      macroContext: "Gold price stabilization boosting buyer confidence.",
    },
    targetPrice: "₹3,850.00 (+10.6%)",
    stopLoss: "₹3,350.00 (-3.7%)",
    timeHorizon: "2-4 Weeks Swing",
  },
  {
    ticker: "NTPC",
    name: "NTPC Ltd",
    price: "₹412.00",
    change: "+1.9%",
    isPositive: true,
    sector: "Power Generation & Green Energy",
    category: "NIFTY 50",
    data: { volatility: 32, fiiFlow: 1540, momentum: 2.1 },
    quantAnalysis: {
      greeks: "Delta +0.60, steady call open interest expansion at 400",
      pcr: 1.24,
      support: "₹395",
      resistance: "₹440",
      summary: "NTPC Green Energy IPO de-bottlenecking clean power valuation.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/DRHP: NTPC Green Energy subsidiary IPO cleared.",
      governanceScore: 92,
      insiderActivity: "Govt holding 51.1%; high dividend yield of 3.8%.",
      auditorNotes: "Standard clean power utility statutory audit.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Power Inflow: +₹1,540 Cr steady utility buying.",
      socialScore: 81,
      newsPolarity: "90% Positive on peak Indian electricity demand growth.",
      macroContext: "National peak power demand crossing 250GW.",
    },
    targetPrice: "₹465.00 (+12.8%)",
    stopLoss: "₹390.00 (-5.3%)",
    timeHorizon: "1-3 Months Safe Yield",
  },
  {
    ticker: "IREDA",
    name: "Indian Renewable Energy Dev Agency",
    price: "₹235.00",
    change: "+4.5%",
    isPositive: true,
    sector: "Renewable NBFC",
    category: "MIDCAP ALPHA",
    data: { volatility: 68, fiiFlow: 1650, momentum: 4.6 },
    quantAnalysis: {
      greeks: "Delta +0.80, massive retail & institutional volume surge",
      pcr: 1.44,
      support: "₹218",
      resistance: "₹265",
      summary: "Navratna PSU status + record loan book sanctions for solar/wind.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/IREDA-Q2: Net NPAs below 0.99%, loan book ₹65k Cr.",
      governanceScore: 89,
      insiderActivity: "Govt 75% holding, zero promoter pledge liabilities.",
      auditorNotes: "Pristine green financing audit compliance.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII & DII Inflow: +₹1,650 Cr clean energy credit growth.",
      socialScore: 92,
      newsPolarity: "94% Bullish on sovereign green bonds issuance.",
      macroContext: "Direct financing arm of Ministry of New & Renewable Energy.",
    },
    targetPrice: "₹285.00 (+21.2%)",
    stopLoss: "₹215.00 (-8.5%)",
    timeHorizon: "2-4 Weeks High Beta",
  },
  {
    ticker: "DIXON",
    name: "Dixon Technologies (India) Ltd",
    price: "₹14,200.00",
    change: "+3.9%",
    isPositive: true,
    sector: "Electronics Manufacturing (EMS)",
    category: "NIFTY NEXT 50",
    data: { volatility: 56, fiiFlow: 2100, momentum: 4.2 },
    quantAnalysis: {
      greeks: "Delta +0.77, smartphone PLI export manufacturing boom",
      pcr: 1.39,
      support: "₹13,500",
      resistance: "₹15,800",
      summary: "Top Indian electronics manufacturing services (EMS) contractor.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/2026/DIX-PLI: Smartphone exports crossing 30M units milestone.",
      governanceScore: 90,
      insiderActivity: "Promoter shareholding stable, key OEM contracts added.",
      auditorNotes: "Clean operating cash flow and working capital audit.",
    },
    sentimentAnalysis: {
      fiiFlowText: "FII Inflow: +₹2,100 Cr electronics PLI allocation.",
      socialScore: 89,
      newsPolarity: "96% Bullish on global hardware supply chain shift to India.",
      macroContext: "Government electronics production incentive schemes.",
    },
    targetPrice: "₹16,500.00 (+16.2%)",
    stopLoss: "₹13,400.00 (-5.6%)",
    timeHorizon: "1-3 Months Growth",
  },
  {
    ticker: "VEDL",
    name: "Vedanta Ltd",
    price: "₹480.00",
    change: "+1.7%",
    isPositive: true,
    sector: "Metals & Natural Resources",
    category: "NIFTY NEXT 50",
    data: { volatility: 62, fiiFlow: 1100, momentum: 2.4 },
    quantAnalysis: {
      greeks: "Delta +0.60, high dividend yield cushion",
      pcr: 1.15,
      support: "₹455",
      resistance: "₹520",
      summary: "Zinc, Aluminium & Oil natural resource demerger value unlocking.",
    },
    regulatoryAnalysis: {
      sebiFilings: "SEBI/NCLT: 6-way corporate demerger scheme in advanced approvals.",
      governanceScore: 79,
      insiderActivity: "Promoter debt successfully refinanced with global bondholders.",
      auditorNotes: "Clean parent debt reduction disclosures.",
    },
    sentimentAnalysis: {
      fiiFlowText: "Net Inflow: +₹1,100 Cr dividend & commodity play.",
      socialScore: 78,
      newsPolarity: "82% Positive on aluminium cost-of-production leadership.",
      macroContext: "Base metal pricing firming on global grid transition.",
    },
    targetPrice: "₹550.00 (+14.5%)",
    stopLoss: "₹450.00 (-6.2%)",
    timeHorizon: "1-3 Months Dividend Value",
  },
];

// Helper to auto-generate the remaining dataset dynamically up to 150 top Indian companies
const BASE_TICKERS = [
  { t: "AXISBANK", n: "Axis Bank Ltd", s: "Banking & Finance", c: "NIFTY 50", p: 1220, v: 34, f: 1650, m: 2.1 },
  { t: "BAJFINANCE", n: "Bajaj Finance Ltd", s: "NBFC / Retail Credit", c: "NIFTY 50", p: 7150, v: 42, f: 1950, m: 2.8 },
  { t: "BAJAJFINSV", n: "Bajaj Finserv Ltd", s: "Financial Services", c: "NIFTY 50", p: 1840, v: 36, f: 1250, m: 1.9 },
  { t: "HINDUNILVR", n: "Hindustan Unilever Ltd", s: "FMCG Consumer", c: "SENSEX 30", p: 2680, v: 20, f: 880, m: 0.8 },
  { t: "COALINDIA", n: "Coal India Ltd", s: "Mining & Energy", c: "NIFTY 50", p: 485, v: 35, f: 1420, m: 1.8 },
  { t: "ONGC", n: "Oil & Natural Gas Corp", s: "Oil & Gas Exploration", c: "NIFTY 50", p: 295, v: 38, f: 1300, m: 1.6 },
  { t: "POWERGRID", n: "Power Grid Corp of India", s: "Power Transmission", c: "NIFTY 50", p: 335, v: 22, f: 1100, m: 1.2 },
  { t: "M&M", n: "Mahindra & Mahindra Ltd", s: "Automotive & Tractors", c: "NIFTY 50", p: 2890, v: 40, f: 2350, m: 3.4 },
  { t: "ASIANPAINT", n: "Asian Paints Ltd", s: "Paints & Decor", c: "SENSEX 30", p: 2540, v: 28, f: 720, m: 0.5 },
  { t: "HINDALCO", n: "Hindalco Industries Ltd", s: "Aluminium & Copper", c: "NIFTY 50", p: 685, v: 52, f: 1540, m: 2.6 },
  { t: "GRASIM", n: "Grasim Industries Ltd", s: "Cement & Chemicals", c: "NIFTY 50", p: 2680, v: 36, f: 1150, m: 1.7 },
  { t: "TECHM", n: "Tech Mahindra Ltd", s: "IT & Telecom", c: "NIFTY 50", p: 1680, v: 44, f: 1480, m: 2.3 },
  { t: "INDUSINDBK", n: "IndusInd Bank Ltd", s: "Private Banking", c: "NIFTY 50", p: 1420, v: 46, f: 1120, m: 1.4 },
  { t: "NESTLEIND", n: "Nestle India Ltd", s: "Food & FMCG", c: "SENSEX 30", p: 2450, v: 19, f: 650, m: 0.6 },
  { t: "CIPLA", n: "Cipla Ltd", s: "Pharmaceuticals", c: "NIFTY 50", p: 1580, v: 25, f: 1350, m: 1.5 },
  { t: "WIPRO", n: "Wipro Ltd", s: "Information Technology", c: "NIFTY 50", p: 545, v: 38, f: 950, m: 1.2 },
  { t: "JSWSTEEL", n: "JSW Steel Ltd", s: "Steel & Infrastructure", c: "NIFTY 50", p: 985, v: 48, f: 1280, m: 1.9 },
  { t: "HCLTECH", n: "HCL Technologies Ltd", s: "IT & Engineering", c: "NIFTY 50", p: 1820, v: 29, f: 1750, m: 2.2 },
  { t: "TATACONSUM", n: "Tata Consumer Products", s: "Consumer Beverages", c: "NIFTY 50", p: 1180, v: 31, f: 1400, m: 1.8 },
  { t: "DRREDDY", n: "Dr Reddy's Laboratories", s: "Pharmaceuticals", c: "NIFTY 50", p: 6680, v: 27, f: 1280, m: 1.4 },
  { t: "ADANIPORTS", n: "Adani Ports & SEZ Ltd", s: "Ports & Logistics", c: "NIFTY 50", p: 1440, v: 45, f: 2150, m: 2.9 },
  { t: "BAJAJ-AUTO", n: "Bajaj Auto Ltd", s: "2-Wheeler Auto & EV", c: "NIFTY 50", p: 10450, v: 42, f: 1890, m: 2.7 },
  { t: "HEROMOTOCO", n: "Hero MotoCorp Ltd", s: "2-Wheeler Auto", c: "NIFTY 50", p: 5480, v: 35, f: 1120, m: 1.6 },
  { t: "APOLLOHOSP", n: "Apollo Hospitals Enterprise", s: "Healthcare Services", c: "NIFTY 50", p: 7120, v: 38, f: 1650, m: 2.3 },
  { t: "EICHERMOT", n: "Eicher Motors Ltd (Royal Enfield)", s: "Automobile", c: "NIFTY 50", p: 4890, v: 37, f: 1550, m: 2.1 },
  { t: "DIVISLAB", n: "Divi's Laboratories Ltd", s: "API Pharma", c: "NIFTY 50", p: 5650, v: 41, f: 1720, m: 2.4 },
  { t: "BPCL", n: "Bharat Petroleum Corp Ltd", s: "Oil Refining & Marketing", c: "NIFTY 50", p: 355, v: 44, f: 1200, m: 1.5 },
  { t: "LTIM", n: "LTIMindtree Ltd", s: "IT Services", c: "NIFTY 50", p: 6150, v: 43, f: 1450, m: 2.2 },
  { t: "BRITANNIA", n: "Britannia Industries Ltd", s: "FMCG Bakery", c: "NIFTY 50", p: 5850, v: 22, f: 920, m: 0.9 },
  { t: "SHRIRAMFIN", n: "Shriram Finance Ltd", s: "Commercial Vehicle NBFC", c: "NIFTY 50", p: 3450, v: 46, f: 1890, m: 2.8 },
  { t: "SIEMENS", n: "Siemens Ltd", s: "Capital Goods & Energy", c: "NIFTY NEXT 50", p: 7650, v: 42, f: 2200, m: 3.1 },
  { t: "DLF", n: "DLF Ltd", s: "Real Estate Development", c: "NIFTY NEXT 50", p: 890, v: 54, f: 1950, m: 3.3 },
  { t: "AMBUJACEM", n: "Ambuja Cements Ltd", s: "Cement & Building Materials", c: "NIFTY NEXT 50", p: 615, v: 38, f: 1350, m: 1.8 },
  { t: "BANKBARODA", n: "Bank of Baroda", s: "PSU Banking", c: "NIFTY NEXT 50", p: 255, v: 42, f: 1420, m: 1.9 },
  { t: "IRFC", n: "Indian Railway Finance Corp", s: "Railways Infrastructure NBFC", c: "NIFTY NEXT 50", p: 165, v: 62, f: 1550, m: 3.8 },
  { t: "PFC", n: "Power Finance Corporation", s: "Power Infrastructure NBFC", c: "NIFTY NEXT 50", p: 510, v: 48, f: 1750, m: 2.6 },
  { t: "RECLTD", n: "REC Ltd", s: "Power Finance", c: "NIFTY NEXT 50", p: 545, v: 49, f: 1820, m: 2.7 },
  { t: "INDIGO", n: "InterGlobe Aviation Ltd", s: "Aviation & Airlines", c: "NIFTY NEXT 50", p: 4680, v: 51, f: 2150, m: 3.2 },
  { t: "PNB", n: "Punjab National Bank", s: "PSU Banking", c: "NIFTY NEXT 50", p: 112, v: 55, f: 1250, m: 1.7 },
  { t: "TVSMOTOR", n: "TVS Motor Company Ltd", s: "2-Wheeler Auto & EV", c: "NIFTY NEXT 50", p: 2480, v: 43, f: 1880, m: 2.9 },
  { t: "HAVELLS", n: "Havells India Ltd", s: "Consumer Electricals", c: "NIFTY NEXT 50", p: 1920, v: 36, f: 1450, m: 2.0 },
  { t: "GODREJCP", n: "Godrej Consumer Products", s: "FMCG Personal Care", c: "NIFTY NEXT 50", p: 1340, v: 28, f: 1150, m: 1.4 },
  { t: "CGPOWER", n: "CG Power and Industrial Solutions", s: "Industrial Motors & Semiconductors", c: "NIFTY NEXT 50", p: 725, v: 58, f: 2050, m: 3.9 },
  { t: "ABB", n: "ABB India Ltd", s: "Robotics & Heavy Electricals", c: "NIFTY NEXT 50", p: 8150, v: 45, f: 2280, m: 3.4 },
  { t: "UNIONBANK", n: "Union Bank of India", s: "PSU Banking", c: "NIFTY NEXT 50", p: 128, v: 48, f: 1100, m: 1.5 },
  { t: "CUMMINSIND", n: "Cummins India Ltd", s: "Engines & Gensets", c: "NIFTY NEXT 50", p: 3850, v: 41, f: 1680, m: 2.5 },
  { t: "IOC", n: "Indian Oil Corporation", s: "Oil & Gas Refining", c: "NIFTY NEXT 50", p: 175, v: 39, f: 1050, m: 1.3 },
  { t: "IDFCFIRSTB", n: "IDFC First Bank Ltd", s: "Private Banking", c: "NIFTY NEXT 50", p: 76, v: 44, f: 1200, m: 1.8 },
  { t: "POLICYBZR", n: "PB Fintech Ltd (Policybazaar)", s: "Insurance Fintech", c: "HIGH BETA & F&O", p: 1780, v: 66, f: 1850, m: 4.2 },
  { t: "NYKAA", n: "FSN E-Commerce Ventures", s: "Beauty E-Commerce", c: "HIGH BETA & F&O", p: 205, v: 64, f: 1250, m: 3.2 },
  { t: "CDSL", n: "Central Depository Services Ltd", s: "Capital Market Infrastructure", c: "MIDCAP ALPHA", p: 1580, v: 58, f: 1950, m: 3.9 },
  { t: "ANGELONE", n: "Angel One Ltd", s: "Digital Retail Broking", c: "MIDCAP ALPHA", p: 2850, v: 65, f: 1680, m: 3.7 },
  { t: "BSE", n: "BSE Ltd (Stock Exchange)", s: "Derivatives & Exchange", c: "MIDCAP ALPHA", p: 4850, v: 70, f: 2750, m: 4.8 },
  { t: "KPITTECH", n: "KPIT Technologies Ltd", s: "Automotive Software AI", c: "MIDCAP ALPHA", p: 1740, v: 55, f: 1780, m: 3.5 },
  { t: "RVNL", n: "Rail Vikas Nigam Ltd", s: "Rail Infrastructure PSU", c: "MIDCAP ALPHA", p: 475, v: 76, f: 1920, m: 4.5 },
  { t: "MAZDOCK", n: "Mazagon Dock Shipbuilders", s: "Submarines & Warships Defense", c: "MIDCAP ALPHA", p: 4450, v: 72, f: 2350, m: 4.6 },
  { t: "KAYNES", n: "Kaynes Technology India", s: "IoT & Electronics Manufacturing", c: "MIDCAP ALPHA", p: 5450, v: 68, f: 1880, m: 4.1 },
  { t: "MOTHERSON", n: "Samvardhana Motherson International", s: "Auto Wiring & Components", c: "NIFTY NEXT 50", p: 195, v: 46, f: 1450, m: 2.2 },
  { t: "LODHA", n: "Macrotech Developers (Lodha)", s: "Luxury Real Estate", c: "NIFTY NEXT 50", p: 1280, v: 50, f: 1650, m: 2.8 },
  { t: "PERSISTENT", n: "Persistent Systems Ltd", s: "Digital Engineering IT", c: "NIFTY NEXT 50", p: 5650, v: 48, f: 1920, m: 3.0 },
  { t: "POLYCAB", n: "Polycab India Ltd", s: "Cables & Fast Moving Electricals", c: "NIFTY NEXT 50", p: 6890, v: 45, f: 1850, m: 2.7 },
  { t: "CHOLAFIN", n: "Cholamandalam Investment", s: "Vehicle & SME Finance", c: "NIFTY NEXT 50", p: 1540, v: 41, f: 1680, m: 2.4 },
  { t: "MAXHEALTH", n: "Max Healthcare Institute", s: "Hospitals & Diagnostics", c: "NIFTY NEXT 50", p: 980, v: 38, f: 1750, m: 2.5 },
  { t: "TORNTPHARM", n: "Torrent Pharmaceuticals", s: "Branded Formulations Pharma", c: "NIFTY NEXT 50", p: 3350, v: 31, f: 1350, m: 1.8 },
  { t: "BOSCHLTD", n: "Bosch Ltd", s: "Automotive Tech & Sensors", c: "NIFTY NEXT 50", p: 34500, v: 33, f: 1250, m: 1.5 },
  { t: "COLPAL", n: "Colgate-Palmolive India", s: "Oral Care FMCG", c: "NIFTY NEXT 50", p: 3680, v: 24, f: 980, m: 1.1 },
  { t: "PIDILITIND", n: "Pidilite Industries Ltd (Fevicol)", s: "Adhesives & Chemicals", c: "NIFTY NEXT 50", p: 3150, v: 27, f: 1120, m: 1.3 },
  { t: "BERGEPAINT", n: "Berger Paints India Ltd", s: "Decorative Coatings", c: "NIFTY NEXT 50", p: 540, v: 32, f: 890, m: 1.0 },
  { t: "AUROPHARMA", n: "Aurobindo Pharma Ltd", s: "Generic Injectables", c: "NIFTY NEXT 50", p: 1480, v: 42, f: 1520, m: 2.1 },
  { t: "LUPIN", n: "Lupin Ltd", s: "Inhalation & Generics Pharma", c: "NIFTY NEXT 50", p: 2180, v: 39, f: 1620, m: 2.3 },
  { t: "INDHOTEL", n: "The Indian Hotels Co (Taj)", s: "Luxury Hospitality", c: "NIFTY NEXT 50", p: 720, v: 44, f: 1980, m: 3.1 },
  { t: "OBEROIRLTY", n: "Oberoi Realty Ltd", s: "Premium Residential Real Estate", c: "MIDCAP ALPHA", p: 1890, v: 46, f: 1550, m: 2.6 },
  { t: "COFORGE", n: "Coforge Ltd", s: "Travel & Insurance IT", c: "MIDCAP ALPHA", p: 7850, v: 52, f: 1950, m: 3.3 },
  { t: "FEDERALBNK", n: "Federal Bank Ltd", s: "Private Regional Bank", c: "MIDCAP ALPHA", p: 198, v: 36, f: 1250, m: 1.8 },
  { t: "DEEPAKNTR", n: "Deepak Nitrite Ltd", s: "Specialty Chemicals", c: "MIDCAP ALPHA", p: 2850, v: 45, f: 1350, m: 2.0 },
  { t: "TATACOMM", n: "Tata Communications Ltd", s: "Cloud & Global Telecommunications", c: "MIDCAP ALPHA", p: 2050, v: 40, f: 1480, m: 2.1 },
  { t: "APLAPOLLO", n: "APL Apollo Tubes Ltd", s: "Structural Steel Tubes", c: "MIDCAP ALPHA", p: 1520, v: 44, f: 1380, m: 2.2 },
  { t: "ASTRAL", n: "Astral Ltd", s: "Pipes & Building Adhesives", c: "MIDCAP ALPHA", p: 1980, v: 35, f: 1150, m: 1.6 },
  { t: "SUPREMEIND", n: "Supreme Industries Ltd", s: "Plastics & Piping", c: "MIDCAP ALPHA", p: 5250, v: 33, f: 1180, m: 1.5 },
  { t: "BALKRISIND", n: "Balkrishna Industries Ltd", s: "Off-Highway Tires", c: "MIDCAP ALPHA", p: 3050, v: 37, f: 1280, m: 1.7 },
  { t: "MRF", n: "MRF Ltd", s: "Tires & Rubber", c: "MIDCAP ALPHA", p: 142000, v: 25, f: 1050, m: 1.1 },
  { t: "MUTHOOTFIN", n: "Muthoot Finance Ltd", s: "Gold Loan NBFC", c: "MIDCAP ALPHA", p: 1980, v: 39, f: 1650, m: 2.4 },
  { t: "MANAPPURAM", n: "Manappuram Finance Ltd", s: "Gold & Microfinance", c: "MIDCAP ALPHA", p: 175, v: 48, f: 980, m: 1.5 },
  { t: "PAGEIND", n: "Page Industries Ltd (Jockey)", s: "Apparel & Innerwear", c: "MIDCAP ALPHA", p: 44500, v: 32, f: 1120, m: 1.4 },
  { t: "JUBLFOOD", n: "Jubilant FoodWorks (Domino's)", s: "Quick Service Restaurants", c: "MIDCAP ALPHA", p: 620, v: 42, f: 1350, m: 1.9 },
  { t: "DEVYANI", n: "Devyani International (KFC)", s: "QSR Franchises", c: "MIDCAP ALPHA", p: 185, v: 46, f: 1150, m: 1.8 },
  { t: "ZEEL", n: "Zee Entertainment Enterprises", s: "Media & Broadcast", c: "HIGH BETA & F&O", p: 125, v: 82, f: -1850, m: -3.2 },
  { t: "YESBANK", n: "Yes Bank Ltd", s: "Private Banking Recovery", c: "HIGH BETA & F&O", p: 22.5, v: 68, f: 850, m: 1.2 },
  { t: "IDEA", n: "Vodafone Idea Ltd", s: "Telecom Services", c: "HIGH BETA & F&O", p: 8.4, v: 92, f: -2100, m: -4.5 },
  { t: "SAIL", n: "Steel Authority of India Ltd", s: "PSU Steel", c: "HIGH BETA & F&O", p: 132, v: 64, f: -850, m: -0.9 },
  { t: "NMDC", n: "NMDC Ltd", s: "Iron Ore Mining", c: "NIFTY NEXT 50", p: 235, v: 49, f: 1450, m: 2.2 },
  { t: "NATIONALUM", n: "National Aluminium Co Ltd", s: "Alumina & Aluminium Mining", c: "HIGH BETA & F&O", p: 220, v: 62, f: 1680, m: 3.4 },
  { t: "HINDPETRO", n: "Hindustan Petroleum Corp", s: "Oil Marketing", c: "HIGH BETA & F&O", p: 385, v: 54, f: 1220, m: 1.8 },
  { t: "GAIL", n: "GAIL (India) Ltd", s: "Natural Gas Transmission", c: "NIFTY NEXT 50", p: 215, v: 38, f: 1420, m: 2.1 },
  { t: "PETRONET", n: "Petronet LNG Ltd", s: "LNG Regasification", c: "MIDCAP ALPHA", p: 345, v: 34, f: 1250, m: 1.6 },
  { t: "OIL", n: "Oil India Ltd", s: "Upstream Oil Exploration", c: "MIDCAP ALPHA", p: 510, v: 58, f: 1750, m: 3.2 },
  { t: "IRCTC", n: "Indian Railway Catering & Tourism", s: "Railway Ticketing & Tourism Monopoly", c: "NIFTY NEXT 50", p: 910, v: 42, f: 1480, m: 1.9 },
  { t: "CONCOR", n: "Container Corporation of India", s: "Logistics & Multimodal Transport", c: "MIDCAP ALPHA", p: 980, v: 39, f: 1380, m: 1.8 },
  { t: "GMRINFRA", n: "GMR Airports Infrastructure Ltd", s: "Airport Operator (Delhi/Hyd)", c: "MIDCAP ALPHA", p: 92, v: 64, f: 1650, m: 3.5 },
  { t: "PRESTIGE", n: "Prestige Estates Projects Ltd", s: "Real Estate Commercial & Residential", c: "MIDCAP ALPHA", p: 1780, v: 56, f: 1850, m: 3.3 },
  { t: "GODREJPROP", n: "Godrej Properties Ltd", s: "Real Estate", c: "NIFTY NEXT 50", p: 3120, v: 52, f: 1950, m: 3.1 },
  { t: "BRIGADE", n: "Brigade Enterprises Ltd", s: "Real Estate & Hospitality", c: "MIDCAP ALPHA", p: 1280, v: 49, f: 1450, m: 2.6 },
  { t: "PHOENIXLTD", n: "The Phoenix Mills Ltd", s: "Retail Malls & Commercial Assets", c: "MIDCAP ALPHA", p: 1650, v: 36, f: 1550, m: 2.2 },
  { t: "EXIDEIND", n: "Exide Industries Ltd", s: "EV Lithium Battery Giga-Factory", c: "MIDCAP ALPHA", p: 485, v: 59, f: 1780, m: 3.6 },
  { t: "AMARAJABAT", n: "Amara Raja Energy & Mobility", s: "Lead Acid & EV Batteries", c: "MIDCAP ALPHA", p: 1340, v: 61, f: 1620, m: 3.4 },
  { t: "SONACOMS", n: "Sona BLW Precision Forgings", s: "EV Driveline Systems", c: "MIDCAP ALPHA", p: 710, v: 48, f: 1680, m: 2.8 },
  { t: "UNOMINDA", n: "Uno Minda Ltd", s: "Auto Electronics & Switches", c: "MIDCAP ALPHA", p: 1140, v: 44, f: 1580, m: 2.7 },
  { t: "ENDURANCE", n: "Endurance Technologies Ltd", s: "2W/3W Auto Parts & Brakes", c: "MIDCAP ALPHA", p: 2450, v: 38, f: 1280, m: 2.0 },
  { t: "SCHAEFFLER", n: "Schaeffler India Ltd", s: "Precision Bearings", c: "MIDCAP ALPHA", p: 3950, v: 35, f: 1220, m: 1.7 },
  { t: "SKFINDIA", n: "SKF India Ltd", s: "Industrial Bearings", c: "MIDCAP ALPHA", p: 5150, v: 32, f: 1150, m: 1.4 },
  { t: "TIMKEN", n: "Timken India Ltd", s: "Roller Bearings", c: "MIDCAP ALPHA", p: 3680, v: 36, f: 1250, m: 1.6 },
  { t: "AIAENG", n: "AIA Engineering Ltd", s: "High Chrome Grinding Media", c: "MIDCAP ALPHA", p: 4550, v: 28, f: 1100, m: 1.3 },
  { t: "THERMAX", n: "Thermax Ltd", s: "Clean Energy Boilers & Decarbonization", c: "MIDCAP ALPHA", p: 5250, v: 46, f: 1750, m: 2.9 },
  { t: "VOLTAS", n: "Voltas Ltd (A Tata Enterprise)", s: "Air Conditioners & Cooling", c: "MIDCAP ALPHA", p: 1780, v: 48, f: 1620, m: 2.7 },
  { t: "BLUESTARCO", n: "Blue Star Ltd", s: "Commercial Refrigeration", c: "MIDCAP ALPHA", p: 1890, v: 45, f: 1580, m: 2.6 },
  { t: "CROMPTON", n: "Crompton Greaves Consumer Electricals", s: "Fans & Home Appliances", c: "MIDCAP ALPHA", p: 410, v: 37, f: 1250, m: 1.7 },
  { t: "WHIRLPOOL", n: "Whirlpool of India Ltd", s: "Home Appliances", c: "MIDCAP ALPHA", p: 2150, v: 41, f: 1120, m: 1.5 },
  { t: "METROPOLIS", n: "Metropolis Healthcare Ltd", s: "Diagnostic Pathology Labs", c: "MIDCAP ALPHA", p: 2250, v: 44, f: 1450, m: 2.3 },
  { t: "LALPATHLAB", n: "Dr Lal PathLabs Ltd", s: "Medical Diagnostics", c: "MIDCAP ALPHA", p: 3250, v: 39, f: 1420, m: 2.1 },
  { t: "FORTIS", n: "Fortis Healthcare Ltd", s: "Hospital Chains", c: "MIDCAP ALPHA", p: 560, v: 42, f: 1680, m: 2.6 },
  { t: "SYNGENE", n: "Syngene International Ltd", s: "Contract Research Pharma (CRO)", c: "MIDCAP ALPHA", p: 890, v: 36, f: 1350, m: 1.9 },
  { t: "GLENMARK", n: "Glenmark Pharmaceuticals Ltd", s: "Respiratory & Dermatology", c: "MIDCAP ALPHA", p: 1680, v: 45, f: 1550, m: 2.4 },
  { t: "ALKEM", n: "Alkem Laboratories Ltd", s: "Anti-Infectives & Formulations", c: "MIDCAP ALPHA", p: 5750, v: 33, f: 1380, m: 1.7 },
  { t: "IPCALAB", n: "IPCA Laboratories Ltd", s: "Active Pharma Ingredients", c: "MIDCAP ALPHA", p: 1580, v: 38, f: 1420, m: 2.0 },
  { t: "NATCOPHARM", n: "Natco Pharma Ltd", s: "Oncology & Specialty Pharma", c: "MIDCAP ALPHA", p: 1480, v: 52, f: 1650, m: 2.8 },
  { t: "GLAXO", n: "GlaxoSmithKline Pharmaceuticals", s: "Vaccines & Branded Pharma", c: "MIDCAP ALPHA", p: 2850, v: 26, f: 1050, m: 1.1 },
  { t: "PFIZER", n: "Pfizer Ltd (India)", s: "Global Pharma Portfolio", c: "MIDCAP ALPHA", p: 5450, v: 24, f: 980, m: 0.9 },
  { t: "SANOFI", n: "Sanofi India Ltd", s: "Diabetes & Chronic Healthcare", c: "MIDCAP ALPHA", p: 6850, v: 22, f: 920, m: 0.8 },
  { t: "ABBOTINDIA", n: "Abbott India Ltd", s: "Multinational Healthcare", c: "MIDCAP ALPHA", p: 28500, v: 21, f: 1150, m: 1.0 },
];

// Append remaining generated stocks to reach 150 total
export const ALL_150_STOCKS: StockItem[] = [
  ...TOP_150_STOCKS,
  ...BASE_TICKERS.map((stk) => {
    const isBullish = stk.f > 0 && stk.m > 0;
    const changeVal = (stk.m * 0.8).toFixed(1);
    const formattedPrice = `₹${stk.p.toLocaleString("en-IN")}.00`;
    const target = `₹${Math.round(stk.p * (1 + (stk.m > 0 ? stk.m * 0.04 : 0.05))).toLocaleString("en-IN")}.00 (+${(Math.abs(stk.m) * 4).toFixed(1)}%)`;
    const stop = `₹${Math.round(stk.p * 0.96).toLocaleString("en-IN")}.00 (-4.0%)`;

    return {
      ticker: stk.t,
      name: stk.n,
      price: formattedPrice,
      change: `${stk.m >= 0 ? "+" : ""}${changeVal}%`,
      isPositive: stk.m >= 0,
      sector: stk.s,
      category: stk.c as any,
      data: {
        volatility: stk.v,
        fiiFlow: stk.f,
        momentum: stk.m,
        ticker: stk.t,
        name: stk.n,
      },
      quantAnalysis: {
        greeks: `Delta ${stk.m >= 0 ? "+0.64" : "-0.55"}, Put-Call Ratio optimal.`,
        pcr: stk.m >= 0 ? 1.24 : 0.72,
        support: `₹${Math.round(stk.p * 0.97)}`,
        resistance: `₹${Math.round(stk.p * 1.05)}`,
        summary: `Volume-weighted liquidity concentration matching institutional accumulation bands.`,
      },
      regulatoryAnalysis: {
        sebiFilings: `SEBI Verified FY26 compliance disclosures. Zero material statutory penalties recorded.`,
        governanceScore: stk.v > 60 ? 76 : 94,
        insiderActivity: `Promoter equity stable; institutional holding ratio intact.`,
        auditorNotes: `Clean statutory auditor reconciliation report on record.`,
      },
      sentimentAnalysis: {
        fiiFlowText: `Net FII Flow: ${stk.f >= 0 ? "+" : "-"}₹${Math.abs(stk.f).toLocaleString("en-IN")} Cr over recent sessions.`,
        socialScore: stk.m >= 2 ? 88 : stk.m >= 0 ? 74 : 35,
        newsPolarity: `${stk.m >= 0 ? "88% Positive" : "68% Cautious"} market commentary.`,
        macroContext: `Sector momentum aligned with broader domestic capital expenditure trends.`,
      },
      targetPrice: target,
      stopLoss: stop,
      timeHorizon: stk.m >= 3 ? "Momentum Breakout / 1-3 Weeks" : "Core Accumulation / 1-3 Months",
    };
  }),
];
